# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(940, 730)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        #Label judul
        self.labelJudul1 = QtWidgets.QLabel(self.centralwidget)
        self.labelJudul1.setGeometry(QtCore.QRect(190, 10, 550, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelJudul1.setFont(font)
        self.labelJudul1.setObjectName("labelJudul1")
        self.labelJudul2 = QtWidgets.QLabel(self.centralwidget)
        self.labelJudul2.setGeometry(QtCore.QRect(205, 40, 520, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelJudul2.setFont(font)
        self.labelJudul2.setObjectName("labelJudul2")


        #Line pemisah judul dan group box
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 70, 940, 30))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        

        #Group Box raw data
        self.groupBoxRD = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxRD.setGeometry(QtCore.QRect(20, 100, 550, 210))
        self.groupBoxRD.setObjectName("groupBoxRD")
        #Tabel raw data
        self.tableRD = QtWidgets.QTableView(self.groupBoxRD)
        self.tableRD.setGeometry(QtCore.QRect(20, 20, 510, 120))
        self.tableRD.setObjectName("tableRD")
        #Text Edit raw data
        self.TextEditRD = QtWidgets.QPlainTextEdit(self.groupBoxRD)
        self.TextEditRD.setGeometry(QtCore.QRect(20, 160, 290, 30))
        self.TextEditRD.setObjectName("TextEditRD")
        self.TextEditRD.setReadOnly(True)
        #Button import raw data
        self.buttonImportRD = QtWidgets.QPushButton(self.groupBoxRD)
        self.buttonImportRD.setGeometry(QtCore.QRect(330, 160, 90, 30))
        self.buttonImportRD.setObjectName("buttonImportRD")
        #Button preprocessing raw data
        self.buttonPreprocessingRD = QtWidgets.QPushButton(self.groupBoxRD)
        self.buttonPreprocessingRD.setGeometry(QtCore.QRect(440, 160, 90, 30))
        self.buttonPreprocessingRD.setObjectName("buttonPreprocessingRD")


        #Group Box preprocessing
        self.groupBoxPreprocessing = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxPreprocessing.setGeometry(QtCore.QRect(20, 320, 550, 160))
        self.groupBoxPreprocessing.setObjectName("groupBoxPreprocessing")
        #Tabel preprocessing
        self.tablePreprocessing = QtWidgets.QTableView(self.groupBoxPreprocessing)
        self.tablePreprocessing.setGeometry(QtCore.QRect(20, 20, 510, 120))
        self.tablePreprocessing.setObjectName("tablePreprocessing")
        

        #Group Box uji data tunggal
        self.groupBoxUDT = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxUDT.setGeometry(QtCore.QRect(590, 100, 330, 380))
        self.groupBoxUDT.setObjectName("groupBoxUDT")
        #Label jenis kelamin
        self.labelJK = QtWidgets.QLabel(self.groupBoxUDT)
        self.labelJK.setGeometry(QtCore.QRect(20, 20, 80, 30))
        self.labelJK.setAutoFillBackground(True)
        self.labelJK.setObjectName("labelJK")
        #Combo Box jenis kelamin
        self.comboBoxJK = QtWidgets.QComboBox(self.groupBoxUDT)
        self.comboBoxJK.setGeometry(QtCore.QRect(140, 20, 170, 30))
        self.comboBoxJK.setObjectName("comboBoxJK")
        self.comboBoxJK.addItem("")
        self.comboBoxJK.addItem("")
        #Label berat badan
        self.labelBB = QtWidgets.QLabel(self.groupBoxUDT)
        self.labelBB.setGeometry(QtCore.QRect(20, 70, 80, 30))
        self.labelBB.setAutoFillBackground(True)
        self.labelBB.setObjectName("labelBB")
        #Text Edit berat badan
        self.textEditBB = QtWidgets.QPlainTextEdit(self.groupBoxUDT)
        self.textEditBB.setGeometry(QtCore.QRect(140, 70, 170, 30))
        self.textEditBB.setObjectName("textEditBB")
        #Label PB/TB
        self.labelPBTB = QtWidgets.QLabel(self.groupBoxUDT)
        self.labelPBTB.setGeometry(QtCore.QRect(20, 120, 80, 30))
        self.labelPBTB.setAutoFillBackground(True)
        self.labelPBTB.setObjectName("labelPBTB")
        #Text Edit PB/TB
        self.textEditPBTB = QtWidgets.QPlainTextEdit(self.groupBoxUDT)
        self.textEditPBTB.setGeometry(QtCore.QRect(140, 120, 170, 30))
        self.textEditPBTB.setObjectName("textEditPBTB")
        #Label posisi diukur
        self.labelPD = QtWidgets.QLabel(self.groupBoxUDT)
        self.labelPD.setGeometry(QtCore.QRect(20, 170, 80, 30))
        self.labelPD.setAutoFillBackground(True)
        self.labelPD.setObjectName("labelPD")
        #Combo Box posisi diukur
        self.comboBoxPD = QtWidgets.QComboBox(self.groupBoxUDT)
        self.comboBoxPD.setGeometry(QtCore.QRect(140, 170, 170, 30))
        self.comboBoxPD.setObjectName("comboBoxPD")
        self.comboBoxPD.addItem("")
        self.comboBoxPD.addItem("")
        #Label umur
        self.labelUmur = QtWidgets.QLabel(self.groupBoxUDT)
        self.labelUmur.setGeometry(QtCore.QRect(20, 220, 80, 30))
        self.labelUmur.setAutoFillBackground(True)
        self.labelUmur.setObjectName("labelUmur")
        #Text Edit umur
        self.textEditUmur = QtWidgets.QPlainTextEdit(self.groupBoxUDT)
        self.textEditUmur.setGeometry(QtCore.QRect(140, 220, 170, 30))
        self.textEditUmur.setObjectName("textEditUmur")
        #Button proses uji data tunggal
        self.buttonProsesUDT = QtWidgets.QPushButton(self.groupBoxUDT)
        self.buttonProsesUDT.setGeometry(QtCore.QRect(140, 270, 80, 30))
        self.buttonProsesUDT.setObjectName("buttonProsesUDT")
        #Button reset uji data tunggal
        self.buttonResetUDT = QtWidgets.QPushButton(self.groupBoxUDT)
        self.buttonResetUDT.setGeometry(QtCore.QRect(230, 270, 80, 30))
        self.buttonResetUDT.setObjectName("buttonResetUDT")
        #Label status gizi
        self.labelSG = QtWidgets.QLabel(self.groupBoxUDT)
        self.labelSG.setGeometry(QtCore.QRect(20, 330, 80, 30))
        self.labelSG.setAutoFillBackground(True)
        self.labelSG.setObjectName("labelSG")
        #Text Edit status gizi
        self.textEditSG = QtWidgets.QPlainTextEdit(self.groupBoxUDT)
        self.textEditSG.setGeometry(QtCore.QRect(140, 330, 170, 30))
        self.textEditSG.setObjectName("textEditSG")
        self.textEditSG.setReadOnly(True)


        #Group Box pelatihan
        self.groupBoxPelatihan = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxPelatihan.setGeometry(QtCore.QRect(20, 490, 470, 220))
        self.groupBoxPelatihan.setObjectName("groupBoxPelatihan")
        #Label hidden layer
        self.labelHL = QtWidgets.QLabel(self.groupBoxPelatihan)
        self.labelHL.setGeometry(QtCore.QRect(20, 20, 70, 30))
        self.labelHL.setObjectName("labelHL")
        #Combo Box hidden layer
        self.comboBoxHL = QtWidgets.QComboBox(self.groupBoxPelatihan)
        self.comboBoxHL.setGeometry(QtCore.QRect(100, 20, 40, 30))
        self.comboBoxHL.setObjectName("comboBoxHL")
        self.comboBoxHL.addItem("")
        self.comboBoxHL.addItem("")
        #Label fungsi aktivasi hidden layer pertama
        self.labelA1 = QtWidgets.QLabel(self.groupBoxPelatihan)
        self.labelA1.setGeometry(QtCore.QRect(20, 70, 70, 30))
        self.labelA1.setObjectName("labelA1")
        #Combo Box fungsi aktivasi hidden layer pertama
        self.comboBoxA1 = QtWidgets.QComboBox(self.groupBoxPelatihan)
        self.comboBoxA1.setGeometry(QtCore.QRect(100, 70, 70, 30))
        self.comboBoxA1.setObjectName("comboBoxA1")
        self.comboBoxA1.addItem("")
        self.comboBoxA1.addItem("")
        #Label fungsi aktivasi hidden layer kedua
        self.labelA2 = QtWidgets.QLabel(self.groupBoxPelatihan)
        self.labelA2.setGeometry(QtCore.QRect(20, 120, 70, 30))
        self.labelA2.setObjectName("labelA2")
        #Combo Box fungsi aktivasi hidden layer kedua
        self.comboBoxA2 = QtWidgets.QComboBox(self.groupBoxPelatihan)
        self.comboBoxA2.setGeometry(QtCore.QRect(100, 120, 70, 30))
        self.comboBoxA2.setObjectName("comboBoxA2")
        self.comboBoxA2.addItem("")
        self.comboBoxA2.addItem("")
        #Label fungsi training
        self.labelTrain = QtWidgets.QLabel(self.groupBoxPelatihan)
        self.labelTrain.setGeometry(QtCore.QRect(210, 20, 50, 30))
        self.labelTrain.setObjectName("labelTrain")
        #Combo Box fungsi training
        self.comboBoxTrain = QtWidgets.QComboBox(self.groupBoxPelatihan)
        self.comboBoxTrain.setGeometry(QtCore.QRect(270, 20, 70, 30))
        self.comboBoxTrain.setObjectName("comboBoxTrain")
        self.comboBoxTrain.addItem("")
        self.comboBoxTrain.addItem("")
        self.comboBoxTrain.addItem("")
        #Label neuron hidden layer pertama
        self.labelNeuron1 = QtWidgets.QLabel(self.groupBoxPelatihan)
        self.labelNeuron1.setGeometry(QtCore.QRect(210, 70, 50, 30))
        self.labelNeuron1.setObjectName("labelNeuron1")
        #Combo Box neuron hidden layer pertama
        self.comboBoxNeuron1 = QtWidgets.QComboBox(self.groupBoxPelatihan)
        self.comboBoxNeuron1.setGeometry(QtCore.QRect(270, 70, 40, 30))
        self.comboBoxNeuron1.setObjectName("comboBoxNeuron1")
        self.comboBoxNeuron1.addItem("")
        self.comboBoxNeuron1.addItem("")
        self.comboBoxNeuron1.addItem("")
        self.comboBoxNeuron1.addItem("")
        self.comboBoxNeuron1.addItem("")
        self.comboBoxNeuron1.addItem("")
        self.comboBoxNeuron1.addItem("")
        self.comboBoxNeuron1.addItem("")
        self.comboBoxNeuron1.addItem("")
        self.comboBoxNeuron1.addItem("")
        #Label neuron hidden layer kedua
        self.labelNeuron2 = QtWidgets.QLabel(self.groupBoxPelatihan)
        self.labelNeuron2.setGeometry(QtCore.QRect(210, 120, 50, 30))
        self.labelNeuron2.setObjectName("labelNeuron2")
        #Combo Box neuron hidden layer kedua
        self.comboBoxNeuron2 = QtWidgets.QComboBox(self.groupBoxPelatihan)
        self.comboBoxNeuron2.setGeometry(QtCore.QRect(270, 120, 40, 30))
        self.comboBoxNeuron2.setObjectName("comboBoxNeuron2")
        self.comboBoxNeuron2.addItem("")
        self.comboBoxNeuron2.addItem("")
        self.comboBoxNeuron2.addItem("")
        self.comboBoxNeuron2.addItem("")
        self.comboBoxNeuron2.addItem("")
        self.comboBoxNeuron2.addItem("")
        self.comboBoxNeuron2.addItem("")
        self.comboBoxNeuron2.addItem("")
        self.comboBoxNeuron2.addItem("")
        self.comboBoxNeuron2.addItem("")
        #Label epoch
        self.labelEpoch = QtWidgets.QLabel(self.groupBoxPelatihan)
        self.labelEpoch.setGeometry(QtCore.QRect(360, 20, 40, 30))
        self.labelEpoch.setObjectName("labelEpoch")
        #Combo Box epoch
        self.comboBoxEpoch = QtWidgets.QComboBox(self.groupBoxPelatihan)
        self.comboBoxEpoch.setGeometry(QtCore.QRect(410, 20, 40, 30))
        self.comboBoxEpoch.setObjectName("comboBoxEpoch")
        self.comboBoxEpoch.addItem("")
        self.comboBoxEpoch.addItem("")
        self.comboBoxEpoch.addItem("")
        self.comboBoxEpoch.addItem("")
        self.comboBoxEpoch.addItem("")
        self.comboBoxEpoch.addItem("")
        #Button proses pelatihan
        self.buttonProsesPelatihan = QtWidgets.QPushButton(self.groupBoxPelatihan)
        self.buttonProsesPelatihan.setGeometry(QtCore.QRect(360, 120, 90, 30))
        self.buttonProsesPelatihan.setObjectName("buttonProsesPelatihan")
        #Button reset pelatihan
        self.buttonResetPelatihan = QtWidgets.QPushButton(self.groupBoxPelatihan)
        self.buttonResetPelatihan.setGeometry(QtCore.QRect(360, 170, 90, 30))
        self.buttonResetPelatihan.setObjectName("buttonResetPelatihan")
        #Label akurasi
        self.labelAkurasi1 = QtWidgets.QLabel(self.groupBoxPelatihan)
        self.labelAkurasi1.setGeometry(QtCore.QRect(20, 170, 70, 30))
        self.labelAkurasi1.setObjectName("labelAkurasi1")
        #Text Edit akurasi
        self.textEditAkurasi = QtWidgets.QPlainTextEdit(self.groupBoxPelatihan)
        self.textEditAkurasi.setGeometry(QtCore.QRect(100, 170, 171, 30))
        self.textEditAkurasi.setObjectName("textEditAkurasi")
        self.textEditAkurasi.setReadOnly(True)
        #Label simbol "%" akurasi
        self.labelAkurasi2 = QtWidgets.QLabel(self.groupBoxPelatihan)
        self.labelAkurasi2.setGeometry(QtCore.QRect(280, 170, 30, 30))
        self.labelAkurasi2.setObjectName("labelAkurasi2")


        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        MainWindow.setWindowTitle(_translate("MainWindow", "KLASIFIKASI STATUS GIZI BALITA"))
        self.labelJudul1.setText(_translate("MainWindow", "KLASIFIKASI STATUS GIZI BALITA MENGGUNAKAN"))
        self.labelJudul2.setText(_translate("MainWindow", "JARINGAN SYARAF TIRUAN BACKPROPAGATION"))

        self.groupBoxRD.setTitle(_translate("MainWindow", "Raw Data"))
        self.buttonImportRD.setText(_translate("MainWindow", "Import Data"))
        self.buttonPreprocessingRD.setText(_translate("MainWindow", "Preprocessing"))

        self.groupBoxUDT.setTitle(_translate("MainWindow", "Uji Data Tunggal"))
        self.labelJK.setText(_translate("MainWindow", "JENIS KELAMIN"))
        self.comboBoxJK.setItemText(0, _translate("MainWindow", "Laki-laki"))
        self.comboBoxJK.setItemText(1, _translate("MainWindow", "Perempuan"))
        self.buttonProsesUDT.setText(_translate("MainWindow", "Proses"))
        self.buttonResetUDT.setText(_translate("MainWindow", "Reset"))
        self.labelSG.setText(_translate("MainWindow", "STATUS GIZI"))
        self.labelUmur.setText(_translate("MainWindow", "UMUR"))
        self.labelPD.setText(_translate("MainWindow", "POSISI DIUKUR"))
        self.labelPBTB.setText(_translate("MainWindow", "PB/TB"))
        self.labelBB.setText(_translate("MainWindow", "BERAT BADAN"))
        self.comboBoxPD.setItemText(0, _translate("MainWindow", "3"))
        self.comboBoxPD.setItemText(1, _translate("MainWindow", "4"))
        self.groupBoxPreprocessing.setTitle(_translate("MainWindow", "Hasil Preprocessing"))
        self.groupBoxPelatihan.setTitle(_translate("MainWindow", "Pelatihan"))
        self.labelHL.setText(_translate("MainWindow", "Hidden Layer"))
        self.labelA1.setText(_translate("MainWindow", "Aktivasi 1"))
        self.comboBoxA1.setItemText(0, _translate("MainWindow", "Tansig"))
        self.comboBoxA1.setItemText(1, _translate("MainWindow", "Logsig"))
        self.comboBoxHL.setItemText(0, _translate("MainWindow", "1"))
        self.comboBoxHL.setItemText(1, _translate("MainWindow", "2"))
        self.comboBoxA2.setItemText(0, _translate("MainWindow", "Tansig"))
        self.comboBoxA2.setItemText(1, _translate("MainWindow", "Logsig"))
        self.labelA2.setText(_translate("MainWindow", "Aktivasi 2"))
        self.labelAkurasi1.setText(_translate("MainWindow", "Akurasi"))
        self.labelAkurasi2.setText(_translate("MainWindow", "%"))
        self.labelTrain.setText(_translate("MainWindow", "Train"))
        self.labelNeuron1.setText(_translate("MainWindow", "Neuron 1"))
        self.labelNeuron2.setText(_translate("MainWindow", "Neuron 2"))
        self.comboBoxNeuron2.setItemText(0, _translate("MainWindow", "5"))
        self.comboBoxNeuron2.setItemText(1, _translate("MainWindow", "10"))
        self.comboBoxNeuron2.setItemText(2, _translate("MainWindow", "15"))
        self.comboBoxNeuron2.setItemText(3, _translate("MainWindow", "20"))
        self.comboBoxNeuron2.setItemText(4, _translate("MainWindow", "25"))
        self.comboBoxNeuron2.setItemText(5, _translate("MainWindow", "30"))
        self.comboBoxNeuron2.setItemText(6, _translate("MainWindow", "35"))
        self.comboBoxNeuron2.setItemText(7, _translate("MainWindow", "40"))
        self.comboBoxNeuron2.setItemText(8, _translate("MainWindow", "45"))
        self.comboBoxNeuron2.setItemText(9, _translate("MainWindow", "50"))
        self.comboBoxNeuron1.setItemText(0, _translate("MainWindow", "5"))
        self.comboBoxNeuron1.setItemText(1, _translate("MainWindow", "10"))
        self.comboBoxNeuron1.setItemText(2, _translate("MainWindow", "15"))
        self.comboBoxNeuron1.setItemText(3, _translate("MainWindow", "20"))
        self.comboBoxNeuron1.setItemText(4, _translate("MainWindow", "25"))
        self.comboBoxNeuron1.setItemText(5, _translate("MainWindow", "30"))
        self.comboBoxNeuron1.setItemText(6, _translate("MainWindow", "35"))
        self.comboBoxNeuron1.setItemText(7, _translate("MainWindow", "40"))
        self.comboBoxNeuron1.setItemText(8, _translate("MainWindow", "45"))
        self.comboBoxNeuron1.setItemText(9, _translate("MainWindow", "50"))
        self.comboBoxTrain.setItemText(0, _translate("MainWindow", "Traingdx"))
        self.comboBoxTrain.setItemText(1, _translate("MainWindow", "Trainlm"))
        self.comboBoxTrain.setItemText(2, _translate("MainWindow", "Traingdm"))
        self.labelEpoch.setText(_translate("MainWindow", "Epoch"))
        self.comboBoxEpoch.setItemText(0, _translate("MainWindow", "50"))
        self.comboBoxEpoch.setItemText(1, _translate("MainWindow", "100"))
        self.comboBoxEpoch.setItemText(2, _translate("MainWindow", "200"))
        self.comboBoxEpoch.setItemText(3, _translate("MainWindow", "250"))
        self.comboBoxEpoch.setItemText(4, _translate("MainWindow", "500"))
        self.comboBoxEpoch.setItemText(5, _translate("MainWindow", "1000"))
        self.buttonProsesPelatihan.setText(_translate("MainWindow", "Proses"))
        self.buttonResetPelatihan.setText(_translate("MainWindow", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
